dist: xenial
language: python
python: 3.6.8
before_install:
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=vocalist
after_success:
  - coveralls