dist: xenial
language: python
python: 3.6.8


before_install:
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev

install:
  - pip install -r requirements.txt

before_script:
  - mindmeld num-parse

script:
  - pytest --cov=vocalist

after_success:
  - coveralls
  - cd ./docs && make github
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/


